### ISSUE TITLE
Docs : requirements

### ISSUE THREAD

**Issue by Davidffry** [cycloidio/inframap#161]
Hi, to run this app you need the minimum requirements which are not specified like *graphviz*. I don't know if some other requirement is necessary.
This is the only issue I have, else great job.

**Comment by xescugc** [comment]
I assume you mean for the `inframap generate state.tfstate | dot -Tpng > graph.png` that you need `dot` to be able to run it no? Because by itself `inframap` does not require anything else.

I'll add a comment into the README that for running those examples you need the libs used outside of `inframap` :).
