### ISSUE TITLE
How to do when the state is stored in a backend ?

### ISSUE THREAD

**Issue by MichaelMure** [cycloidio/inframap#44]
Is there a way to use this tool when the state is stored in a terraform backend like S3 ? There is no .tfstate file in that case.

Thanks :)

**Comment by tormath1** [comment]
Hi @MichaelMure , thanks for raising this issue ! 

That's a good point to raise. Indeed, Terraform supports multiple backends (S3 included) but the goal of `inframap` is to only generate graphs from local `tfstate` (or `HCL`), it's currently up to the user to provide the `tfstate` or `HCL`.

In order to solve your use-case: `inframap` is able to read the `tfstate` (or `HCL`) from the `stdin`, you could simply make the following:

```shell
aws s3 cp s3://bucket/path/to/your/file.tfstate - | inframap generate --tfstate
```

**Comment by tormath1** [comment]
@MichaelMure we added your question to the FAQ in this PR (https://github.com/cycloidio/inframap/pull/46) https://github.com/cycloidio/inframap#does-inframap-support-terraform-backends-

Thanks for your contribution ! :wink:

**Comment by purplepangolin** [comment]
If using some other backend (such as the http backend) then a more general approach is:

```
terraform state pull | inframap generate --tfstate
```

**Comment by xescugc** [comment]
Thanks @purplepangolin I'm gonna add it to the documentation so it's also easily available for people to use :).
